export const kisiKisiData: Record<
  string,
  {
    pp: string[];
    mtk: string[];
    bIndo: string[];
    ipas?: string[];
  }
> = {
  '2': {
    pp: [
      // Sikap di sekolah dan rumah
      'Menunjukkan sikap tertib saat upacara bendera di sekolah',
      'Menunjukkan sikap ramah saat berkenalan dengan tetangga',
      'Menentukan sikap peduli saat tetangga sakit',
      'Menjelaskan kewajiban anak di rumah (misal: membantu orang tua)',
      'Menjelaskan manfaat ruang tamu dan kamar tidur di rumah',
      'Menjelaskan peran ayah dalam keluarga (misal: mencari nafkah)',
      'Menentukan tanggung jawab menjaga kebersihan rumah oleh seluruh anggota keluarga',
      'Menentukan fungsi dapur dalam rumah tangga',

      // Lingkungan dan gotong royong
      'Menentukan cara mencegah banjir (misal: membersihkan saluran air)',
      'Mengidentifikasi kegiatan gotong royong di rumah dan sekolah (misal: membersihkan ruang tamu, kelas, halaman)',
      'Menjelaskan manfaat gotong royong (misal: pekerjaan terasa ringan)',
      'Menentukan kegiatan gotong royong berdasarkan gambar (jalan, jembatan, rumah ibadah)',
      'Menunjukkan contoh sikap kepedulian di sekolah (saling menyayangi, tidak bertengkar)',
      'Menentukan contoh gotong royong yang dilakukan di rumah oleh seluruh keluarga',
      'Menentukan kegiatan gotong royong di lingkungan masyarakat (misal: membangun rumah ibadah)',

      // Pancasila
      'Menjelaskan bunyi sila pertama Pancasila (Ketuhanan Yang Maha Esa)',
      'Menentukan sila ke-2 Pancasila (Kemanusiaan yang adil dan beradab)',

      // Tanggung jawab pribadi
      'Menjelaskan bahwa mengerjakan PR adalah tanggung jawab siswa',
      'Menentukan kegiatan gotong royong di kelas (misal: membersihkan kelas bersama-sama)',
      'Menjelaskan pentingnya hidup rukun dengan tetangga',
    ],
    mtk: [
      'Menghitung banyak benda pada gambar (misalnya jumlah daun = 50)',
      'Menentukan benda sesuai jumlah tertentu (misalnya: 63 kambing)',
      'Menentukan nilai tempat satuan dari bilangan dua angka (misalnya: 59 → satuannya 9)',
      'Menentukan nama bilangan berdasarkan urutan bilangan (menyebutkan dalam kata)',
      'Menghitung selisih antara dua bilangan (misalnya: 50 - 45 = 5)',
      'Mengidentifikasi gambar bangun datar persegi panjang',
      'Membandingkan panjang benda berdasarkan satuan tidak baku (jengkal/tali)',
      'Melakukan penjumlahan dua bilangan dua angka (contoh: 38 + 12 = 50)',
      'Melengkapi urutan bilangan berturut-turut (misalnya: 29, 30, __, __, 33)',
      'Menghitung sisa benda setelah sebagian diberikan (pengurangan sederhana)',
      'Melakukan penjumlahan bilangan kecil dalam konteks cerita (misalnya: 12 anak + 6 anak = 18)',
      'Mengidentifikasi bangun datar berbentuk persegi dari gambar',
      'Menentukan simbol perbandingan bilangan: lebih besar (>), lebih kecil (<), sama dengan (=)',
      'Menuliskan kalimat matematika berdasarkan cerita penjumlahan',
      'Membandingkan berat benda dari gambar/timbangan (lebih berat, lebih ringan)',
      'Menghitung jumlah benda dalam kelompok (mengelompokkan dan menjumlahkan)',
      'Menentukan angka yang hilang dalam pola bilangan (misal: 13, __, 15)',
      'Menjabarkan nilai puluhan dan satuan dari suatu bilangan (misal: 84 = 8 puluhan dan 4 satuan)',
      'Melakukan pengurangan bilangan dua digit (misal: 65 - 14 = 51)',
      'Mengenali nama bangun datar dari gambar (misalnya: segitiga, lingkaran, persegi panjang)',
    ],
    bIndo: [
      'Mengenal dan memahami kata ajaib (terima kasih, tolong, maaf, permisi)',
      'Mengidentifikasi kalimat yang menggunakan tanda seru (!)',
      'Menentukan tempat kerja seseorang sesuai profesinya (misal: petani di sawah)',
      'Menentukan tempat membaca (perpustakaan)',
      'Mengetahui huruf awal nama hewan berdasarkan gambar',
      'Menyusun kata acak menjadi kalimat sederhana yang benar',
      'Melengkapi perkenalan dengan kata yang sesuai (nama, umur, alamat)',
      'Menentukan profesi berdasarkan kegiatan (contoh: koki membuat makanan)',
      'Mengetahui profesi guru sebagai orang yang mengajar di sekolah',
      'Menentukan alat untuk mencuci tangan (sabun dan air mengalir)',
      'Menentukan pekerjaan sesuai aktivitas (misal: nelayan menangkap ikan)',
      'Menyusun kalimat dari kata acak sesuai struktur SPOK sederhana',
      'Menentukan kalimat sopan dalam situasi tertentu (misal: permintaan maaf)',
      'Melengkapi kalimat perintah dengan tanda baca yang sesuai (!)',
      'Menentukan profesi berdasarkan gambar (dokter, guru, polisi, dll)',
      'Menyusun huruf acak menjadi nama hewan (misal: jerapah)',
      'Mengetahui pekerjaan petani sebagai penanam padi',
      'Melengkapi kalimat tanya dengan tanda tanya (?)',
      'Menentukan tempat terjadinya jual beli (pasar)',
    ],
  },
  '3': {
    pp: [
      'Identitas sosial dan personal (contoh: jabatan, suku, agama, ciri psikologis)',
      'Kitab suci dari berbagai agama (Hindu, Buddha, Islam, Kristen, Konghucu, Katolik)',
      'Tempat ibadah berdasarkan agama (Pura, Vihara, Gereja, Masjid)',
      'Asal suku dan pulau (contoh: suku Sunda berasal dari Pulau Jawa)',
      'Makna kerja sama dan gotong royong dalam kehidupan sehari-hari',
      'Nilai-nilai dalam Pancasila (sila ke-1, ke-2, ke-3 dan contohnya)',
      'Semboyan bangsa Indonesia: Bhinneka Tunggal Ika dan asal usulnya (Kitab Sutasoma)',
      'Kepedulian terhadap lingkungan sekolah (contoh: menyapu halaman)',
      'Membaca dan menganalisis denah atau peta lingkungan (letak bangunan dan arah mata angin)',
      'Nama-nama ruangan di sekolah (contoh: perpustakaan untuk meminjam buku)',
      'Kerja sama dalam lingkungan rumah, sekolah, dan masyarakat',
      'Nama-nama benda di ruang dapur (contoh: panci, kompor, wajan)',
      'Hari besar agama-agama (contoh: Tahun Baru Imlek untuk Konghucu)',
      'Suku-suku bangsa di Indonesia (contoh: suku Dayak berasal dari Kalimantan)',
      'Peran dan kedudukan anggota keluarga (contoh: ayah sebagai kepala keluarga)',
      'Agama-agama resmi di Indonesia (6 agama diakui negara)',
      'Contoh keberagaman budaya di Indonesia (tari, rumah adat, pakaian daerah)',
      'Pengertian tetangga dan interaksi sosial di sekitar rumah',
      'Menentukan tetangga berdasarkan denah lingkungan sekitar',
      'Cara menjaga kelestarian lingkungan (contoh: menanam pohon, membersihkan saluran air)',
    ],
    mtk: [
      'Penjumlahan berulang sebagai bentuk dasar perkalian',
      'Konversi bentuk penjumlahan ke perkalian (contoh: 3 x 7 = 3 + 3 + ...)',
      'Masalah kontekstual perkalian sederhana (jumlah total berdasarkan banyak kelompok dan isi per kelompok)',
      'Mengenal bangun datar (contoh: persegi, segitiga, segilima)',
      'Menentukan jumlah sisi pada segitiga',
      'Pengenalan pecahan sederhana (contoh: 1/2, 1/3, 1/4)',
      'Mengenal gambar pecahan (visualisasi pecahan seperti seperempat)',
      'Membaca jam analog (contoh: menunjukkan pukul 07.00)',
      'Menghitung sisi pada bangun ruang (contoh: kubus, balok)',
      'Menghitung titik sudut pada bangun ruang',
      'Menuliskan bentuk perkalian dari penjumlahan berulang (contoh: 8 + 8 + 8 + 8 = 4 x 8)',
      'Mengubah masalah kontekstual ke dalam bentuk perkalian (contoh: 3 jeruk x 6 kantong = 18)',
      'Menentukan pecahan berdasarkan gambar bagian keseluruhan',
      'Identifikasi bangun datar berdasarkan jumlah sisi, sudut, dan titik sudut (contoh: segitiga)',
      'Mengenali pola bangun ruang berdasarkan gambar',
      'Soal cerita perkalian (mobil dan anak), menyatakan dalam bentuk perkalian dan hasilnya',
      'Menentukan pembilang dan penyebut dalam sebuah pecahan',
      'Membaca waktu dari gambar jam',
      'Menggambar bangun datar persegi dan menentukan ukuran sisi',
      'Menggambar balok serta menghitung sisi, sudut, dan rusuk bangun ruang',
    ],
    bIndo: [
      'Pengertian fabel sebagai cerita tentang hewan',
      'Penggunaan tanda baca koma untuk merinci unsur',
      'Antonim atau lawan kata sederhana (contoh: runcing ↔ tumpul)',
      'Makna atau pesan moral dalam pantun',
      "Makna peribahasa 'Berat sama dipikul, ringan sama dijinjing'",
      'Sikap bijak dalam menghadapi keinginan membeli barang',
      'Perilaku menjaga kebersihan lingkungan (membersihkan selokan)',
      'Kata ulang berimbuhan (contoh: sayur-sayuran)',
      'Kalimat imbauan atau ajakan',
      'Jenis sampah organik dan anorganik',
      'Mengenal benda tradisional (kendil)',
      'Penggunaan kata hubung (dan, tetapi, maka)',
      'Pemahaman makna kata berdasarkan gambar (kesepian)',
      'Urutan langkah membuat kerajinan dari barang bekas (mobil dari botol)',
      'Nilai menghargai perbedaan agama dan suku',
      'Menentukan antonim (sakit ↔ sehat, sedikit ↔ banyak)',
      'Pengertian hobi atau kegiatan yang disukai',
      'Identifikasi contoh sampah organik (kulit buah, tulang ikan)',
      'Asal cerita rakyat (Joko Kendil dan Si Gundul)',
      'Contoh pekerjaan yang menghasilkan karya',
      'Membuat peribahasa tentang pengelolaan uang',
      'Mengurutkan gambar cerita (Labih dan Arai)',
      'Langkah-langkah membuat ECO Brick',
      'Penyebab terjadinya banjir',
    ],
  },
  '4': {
    pp: [
      'Menentukan asal suku bangsa di Indonesia (contoh: Betawi dari Jakarta)',
      'Menentukan suku yang berasal dari provinsi tertentu (contoh: Batak dari Sumatra Utara)',
      'Menentukan bahasa yang digunakan untuk berkomunikasi antar suku (jawaban: Bahasa Indonesia)',
      'Mengenal semboyan negara Indonesia (jawaban: Bhinneka Tunggal Ika)',
      'Mengenal asal tari tradisional (contoh: Legong, Kecak dari Bali)',
      'Mengidentifikasi bentuk kebhinekaan di Indonesia (suku, budaya, agama, bahasa)',
      'Mengaitkan pakaian adat dengan daerah asalnya (contoh: Tulang Bawang dari Lampung)',
      'Menentukan sila Pancasila dari peristiwa sehari-hari (contoh: diskusi keluarga = sila ke-4)',
      'Memahami makna keputusan bersama harus dijalankan dengan tanggung jawab',
      'Menunjukkan sikap dalam diskusi sesuai nilai Pancasila (menerima hasil musyawarah)',
      'Mengamalkan produk dalam negeri = semangat cinta tanah air (Pancasila)',
      'Mengidentifikasi permainan tradisional (contoh: enggrang, petak umpet, sapintrong)',
      'Mengenal tokoh perumus Pancasila (Soekarno, Soepomo, dll)',
      'Meneladani karakter positif dari perumus Pancasila (gotong royong, rela berkorban)',
      'Mengenal sikap persatuan dan kesatuan dalam kehidupan sehari-hari',
      'Menuliskan nama bahasa daerah dari suatu provinsi (contoh: Bahasa Batak di Sumut)',
      'Menentukan asal rumah adat (contoh: Rumah Gadang dari Sumatra Barat)',
      'Memahami pentingnya saling menghargai dalam perbedaan',
      'Menentukan asal lagu daerah (contoh: Gundul-Gundul Pacul dari Jawa Tengah)',
      'Mengenali pakaian adat daerah tertentu (contoh: Ulos dari Sumatra Utara)',
      'Menentukan asal lagu daerah (contoh: Ampar-Ampar Pisang dari Kalimantan Selatan)',
      'Menentukan makna sila dalam Pancasila (contoh: bersyukur dan tidak memaksa = sila ke-1)',
      'Menunjukkan pentingnya sikap tolong menolong kepada sesama',
      'Mengenali simbol negara Indonesia (Garuda Pancasila)',
      'Menentukan makna sila ke-4 (lapang dada, musyawarah, menghargai pendapat)',
    ],
    mtk: [
      'Menentukan fungsi alat ukur panjang seperti mistar/penggaris (untuk menggambar garis lurus)',
      'Menentukan satuan baku untuk panjang (cm, m, dll)',
      'Mengidentifikasi alat ukur yang tepat untuk mengukur tinggi badan (meteran/dinding ukur)',
      'Menentukan panjang benda berdasarkan pengukuran gambar (contoh: marker = 13 cm)',
      'Mengubah satuan panjang dari cm ke meter (contoh: 700 cm = 7 m)',
      'Mengenali bangun datar yang memiliki jumlah sisi tertentu (contoh: 3 sisi = segitiga)',
      'Mengenal jenis sudut: sudut lancip (<90°), siku-siku (=90°), tumpul (>90°)',
      'Mengidentifikasi gambar sudut tumpul dari beberapa pilihan gambar sudut',
      'Menentukan ukuran sudut lancip dari sudut refleks (refleks + lancip = 360°)',
      'Menentukan nama bangun datar berdasarkan ciri jumlah sisi dan sudut (contoh: persegi = 4 sisi, 4 sudut)',
      'Membaca data nilai dari diagram batang/tabel/tabel frekuensi (contoh: nilai ulangan sama)',
      'Menentukan jumlah siswa berdasarkan data berat badan pada diagram atau grafik batang',
      'Menjumlahkan data-data kuantitatif sederhana (contoh: jumlah pensil beberapa anak)',
      'Menentukan jumlah siswa berdasarkan nilai dan simbol turus (misal nilai 90 = 8 turus)',
      'Menjumlahkan siswa dari dua nilai yang berbeda pada tabel frekuensi (misal nilai 70 dan 100)',
      'Menuliskan satuan panjang sebagai cm/m (konversi satuan)',
      'Mengubah tinggi gabungan m dan cm menjadi cm saja (misal: 1 m 17 cm = 117 cm)',
      'Mengubah satuan cm ke meter (misal: 130 cm = 1,3 m)',
      'Menjumlahkan satuan berat (misal: 500 gram + 500 gram = 1000 gram)',
      'Menentukan jenis sudut dari besar sudut tertentu (contoh: 90° = siku-siku)',
      'Mengklasifikasikan sudut berdasarkan besarannya (misal: 120° = sudut tumpul)',
      'Menghitung jumlah sisi dari bangun datar sederhana (dari gambar)',
      'Menentukan nilai dari bentuk turus (misal: IIII = 4)',
      'Menggambar atau menentukan jumlah turus dari jumlah data (misal: 9 siswa = IIII IIII I)',
      'Menentukan huruf yang paling banyak muncul dari kata/frasa (statistik huruf)',
    ],
    bIndo: [
      'Menentukan media komunikasi dalam cerita (misal: video call, surat, dll)',
      'Menentukan tokoh dan tempat tinggal tokoh dalam cerita',
      'Menentukan isi atau pesan dalam cerita (berbagi cerita, impian, dll)',
      'Menentukan arti kata dalam konteks (contoh: sebaya = sama umur)',
      'Menentukan siapa pengirim surat dan isi surat pribadi',
      'Menentukan jumlah benda dalam teks surat',
      'Menentukan pengolahan hasil panen dalam teks',
      'Menentukan masalah dalam cerita (contoh: tersesat)',
      'Menentukan perasaan tokoh dalam cerita',
      'Memahami arti kata dalam konteks (contoh: bawaan)',
      'Mengidentifikasi jenis kalimat (anjuran, larangan, perintah, pernyataan)',
      'Mengenali kalimat anjuran dan larangan',
      'Menemukan informasi dalam teks pendek',
      'Memilih kata tanya yang tepat (kapan, mengapa, berapa, siapa)',
      'Menentukan manfaat internet dalam kehidupan sehari-hari',
      'Menentukan sumber informasi digital (misalnya: dari internet)',
      'Menentukan kata kunci untuk mencari informasi di internet',
      'Menentukan peran dalam kegiatan pelaporan (misalnya: sebagai pelapor)',
      'Menentukan fungsi alat (contoh: arloji untuk melihat waktu)',
      'Menggunakan kata depan dengan tepat (di, ke, dari)',
      'Menentukan nama hewan berdasarkan gambar',
      'Melengkapi kalimat dengan kata tanya yang sesuai (berapa, siapa, kapan, dll)',
      'Menentukan sinonim kata (contoh: online = daring)',
      'Menginterpretasi makna emotikon',
      'Menentukan jenis kalimat berdasarkan tanda baca (kalimat langsung)',
    ],
    ipas: [
      'Menentukan alat bantu membaca lokasi (peta, denah, globe, dll)',
      'Menentukan jenis denah (contoh: denah sekolah, rumah sakit, dll)',
      'Menentukan letak suatu tempat berdasarkan denah (misalnya: kantin di sebelah apa)',
      'Mengidentifikasi ketampakan alam (gunung, sungai, danau, lembah)',
      'Mengidentifikasi ketampakan buatan (masjid, terminal, stasiun, jembatan, dll)',
      'Membedakan ketampakan alam dan ketampakan buatan dari daftar pernyataan',
      'Menafsirkan simbol pada denah (contoh: rumah sakit, danau, hutan, SPBU)',
      'Menentukan kedudukan kepala wilayah (contoh: lurah berkedudukan di kelurahan)',
      'Memahami kerja sama antar tingkatan pemerintahan kota/kabupaten',
      'Mengetahui struktur pemerintahan daerah (contoh: wali kota dibantu wakil)',
      'Menentukan letak tempat berdasarkan denah (dalam bentuk pernyataan benar/salah)',
      'Mengenali nama jalan dari peta atau denah',
      'Mencocokkan istilah wilayah dan simbol (contoh: lembah = ketampakan alam)',
      'Mengetahui ibu kota provinsi dan hubungannya (contoh: Sumatera Utara ≠ Banda Aceh)',
      'Mengetahui kota/kabupaten dari suatu provinsi',
      'Menentukan pengertian gambar lokasi (gambar penunjuk disebut denah)',
      'Menafsirkan simbol pada denah (contoh: masjid, pasar, sekolah)',
      'Mengetahui jumlah provinsi di Indonesia',
      'Menyebutkan nama provinsi dari pulau tertentu (contoh: provinsi di Sumatra)',
      'Mengetahui pejabat yang memimpin kabupaten (jawaban: Bupati)',
    ],
  },
  '6': {
    pp: [
      'Penerapan norma dalam kehidupan sehari-hari',
      'Jenis norma yang ditunjukkan oleh gambar',
      'Cara melestarikan kesenian daerah',
      'Penerapan norma agama dalam kehidupan',
      'Identifikasi pelanggaran norma berdasarkan gambar',
      'Sikap terhadap teman dengan logat daerah',
      'Sikap terhadap perbedaan suku, ras, agama',
      'Identifikasi rumah adat (gambar)',
      'Identifikasi rumah adat (gambar)',
      'Nama rumah adat dari gambar',
      'Pasal UUD tentang kebebasan beragama',
      'Letak geografis Indonesia di antara benua',
      'Letak geografis Indonesia di antara samudra',
      'Suku yang ada di Sulawesi',
      'Suku yang terdapat di pulau berdasarkan gambar',
      'Identifikasi suku dari gambar pulau',
      'Asal daerah tarian pada gambar',
      'Nama upacara kematian di Bali',
      'Daerah yang terkenal dengan seni ukir',
      'Ras Kaukasoid',
      'Ras Malayan Mongoloid',
      'Ras Asiatic Mongoloid',
      'Lagu daerah dari Jawa Tengah',
      'Lagu daerah dari Aceh',
      'Asal tari Remo',
      'Asal daerah tari Lenso',
      'Daerah asal alat musik pada gambar',
      'Pengelompokan manusia berdasarkan ciri fisik',
      'Jenis upacara syukur dan perlindungan',
      'Tokoh pengetik naskah proklamasi',
      'Ketua BPUPKI',
      'Tempat pembacaan teks proklamasi',
      'Tokoh Jepang yang membantu merumuskan proklamasi',
      'Lokasi rumah Rengasdengklok milik Djiaw Kie Siong',
      'Lokasi Museum Perumusan Naskah Proklamasi',
    ],
    mtk: [
      'Penjumlahan pecahan dengan penyebut berbeda',
      'Penjumlahan pecahan campuran',
      'Pengurangan pecahan dengan penyebut berbeda',
      'Pengurangan bilangan bulat dengan pecahan',
      'Pembagian pecahan dengan bilangan bulat',
      'Jumlah sisi bangun datar jajaran genjang',
      'Menghitung luas jajaran genjang',
      'Menghitung keliling jajaran genjang',
      'Pengertian dan contoh bangun segi banyak',
      'Identifikasi bangun yang termasuk segi banyak',
      'Identifikasi bangun yang tidak termasuk segi banyak',
      'Menentukan nama bangun berdasarkan jumlah sisi (segi lima, segi tujuh, dll)',
      'Menghitung volume kubus berdasarkan panjang rusuk',
      'Menghitung volume kubus dari soal isian',
      'Menghitung rasio panjang pita dua orang',
      'Menghitung volume tabung dari jari-jari dan tinggi',
      'Mengubah keliling lingkaran menjadi diameter',
      'Mengubah persen ke desimal',
      'Mengubah desimal ke persen',
    ],
    bIndo: [
      'Pengertian ide pokok atau gagasan utama dalam paragraf',
      'Istilah lain dari paragraf',
      'Menentukan gagasan utama dari paragraf deskriptif tentang tari piring',
      'Menentukan gagasan utama paragraf tentang rumah adat Tongkonan',
      "Makna idiom 'gulung tikar'",
      'Identifikasi kata bukan idiom',
      'Pengertian wawancara sebagai percakapan terstruktur',
      'Kalimat tanya yang sesuai dengan kalimat fakta sejarah',
      'Pertanyaan yang sesuai dengan informasi waktu atau tempat',
      'Pertanyaan sesuai informasi suasana dalam kalimat',
      'Contoh penulisan huruf kapital yang benar (nama, tempat, gelar)',
      'Contoh penulisan huruf kapital yang benar (tanggal, bulan)',
      'Contoh penulisan huruf kapital yang benar (jalan, kota)',
      'Penulisan angka Romawi dari angka 36',
      'Pengertian dan ciri-ciri poster',
      'Bagian yang tidak termasuk dalam isi pengumuman',
      'Contoh kalimat perintah yang tepat',
      'Pengertian teks eksplanasi',
      'Ciri khas teks eksplanasi',
      'Contoh kalimat majemuk bertingkat',
      'Konjungsi penyebab dalam kalimat majemuk bertingkat',
      'Contoh kalimat majemuk setara sejalan (kecuali)',
      'Penggunaan kata yang menyatakan tempat',
      'Penggunaan imbuhan pe-an yang tepat (permintaan)',
      'Penggunaan konjungsi antarkalimat (namun, meskipun)',
      'Contoh imbuhan pe-an yang menunjukkan proses',
      'Penggunaan kata hubung yang tepat pada kalimat kompleks',
      'Penggunaan kata hubung kontras (walaupun, meskipun)',
      'Pengertian pidato sebagai kegiatan berbicara di depan umum',
      'Persiapan sebelum berpidato',
      'Bagian-bagian jurnal membaca',
      'Baris ke-3 dan ke-4 dalam pantun merupakan isi',
      'Pola rima dalam pantun (a-b-a-b)',
      'Identifikasi jenis pantun (berdasarkan isi)',
      'Identifikasi sampiran dalam pantun',
    ],
    ipas: [
      'Fungsi rambut halus di hidung dalam sistem pernapasan',
      'Tempat pertukaran oksigen dan karbon dioksida dalam sistem pernapasan',
      'Organ penyerap sari-sari makanan dalam sistem pencernaan',
      'Urutan organ sistem pencernaan manusia',
      'Proses pencernaan kimia dalam organ tubuh',
      'Contoh makanan sumber protein nabati',
      'Ciri-ciri pubertas pada anak laki-laki',
      'Contoh energi alternatif',
      'Ciri masyarakat agraris',
      'Hewan yang dimanfaatkan untuk obat tradisional',
      'Tumbuhan yang digunakan dalam kosmetik',
      'Pembedaan sumber daya hayati dan non hayati',
      'Dampak negatif dari penebangan hutan',
      'Manfaat perairan luas bagi Indonesia',
      'Tindakan yang merusak ekosistem bawah laut',
      'Asal hewan endemik Indonesia dari gambar',
      'Habitat burung maleo',
      'Contoh sumber daya alam yang dapat diperbarui',
      'Jenis tanaman hasil hutan',
      'Fungsi hutan bakau',
      'Contoh kegiatan ekonomi di bidang pertanian',
      'Contoh kegiatan ekonomi di bidang industri',
      'Komoditas unggulan dari provinsi Palembang',
      'Komoditas unggulan dari provinsi Papua',
      'Dampak lingkungan dari pertambangan',
      'Dampak penggunaan bom dalam menangkap ikan',
      'Contoh interaksi positif manusia dengan lingkungan',
      'Dampak hutan gundul terhadap lingkungan',
      'Jenis warisan budaya berdasarkan gambar',
      'Warisan budaya yang dapat dilihat dan diraba',
      'Kegiatan menenun sebagai bentuk warisan budaya',
      'Tradisi Megibung sebagai warisan budaya daerah',
      'Prinsip 3R: Recycle (menggunakan kembali limbah)',
      'Prinsip 3R: Reduce (mengurangi limbah plastik)',
      'Pengertian konservasi sumber daya alam',
    ],
  },
};
